### ISSUE TITLE
Error con usuarios.js (usuarios is not iterable)

### ISSUE THREAD

**Issue by josebellorin** [lucasmoy-dev/Curso-de-Springboot-Hibernate#3]
Agradecido de recibir una mano
![image](https://user-images.githubusercontent.com/104359845/183205543-d9ede702-02c5-4769-8752-f60582ccec6c.png)

**Comment by josebellorin** [comment]
Como no puedo solucionar esto lo que haré será terminar de ver el curso para saber como funcionan las cosas

**Comment by lucasmoyano** [comment]
holaaa, deberías revisar la pestaña "network", y ver si esta haciendo correctamente el llamado al servidor. Quizas no sea error de javascript sino del server, lo vas a poder ver en la pestaña network

**Comment by josebellorin** [comment]
Hola, de verdad muchas gracias por responder y perdona por las molestias
Te adjunto una captura de cada una de las pestañas de network
![image](https://user-images.githubusercontent.com/104359845/183266590-b43c4e36-0dac-41b2-8493-f061aba6ab57.png)
![image](https://user-images.githubusercontent.com/104359845/183266594-8393748c-447f-41e4-a38e-fcbe83e187e7.png)
![image](https://user-images.githubusercontent.com/104359845/183266601-fc233c1b-d80a-4919-ac8c-3f3902cc5b5a.png)
![image](https://user-images.githubusercontent.com/104359845/183266607-51ca1be1-46f7-4648-978b-9f3d7d074518.png)
![image](https://user-images.githubusercontent.com/104359845/183266614-1a804cdd-7d1a-438f-b485-d62f7365f41c.png)
![image](https://user-images.githubusercontent.com/104359845/183266619-421518d5-7c69-46c3-8ff6-79c3ca880807.png)
Muchas gracias de nuevo
Buenas noches

**Comment by josebellorin** [comment]
Del lado de la base de datos tengo este error, podría ser eso?
![image](https://user-images.githubusercontent.com/104359845/183284025-1a255735-c224-4363-872e-b9ab22582834.png)

**Comment by josebellorin** [comment]
> Del lado de la base de datos tengo este error, podría ser eso? ![image](https://user-images.githubusercontent.com/104359845/183284025-1a255735-c224-4363-872e-b9ab22582834.png)

Al final terminé solucionando eso, y me sigue dando el error 500

**Comment by josebellorin** [comment]
También me acabo de dar cuenta de que estoy usando una versión SNAPSHOT de springboot.. 😐
¿Tendrá algo que ver?

**Comment by josebellorin** [comment]
> holaaa, deberías revisar la pestaña "network", y ver si esta haciendo correctamente el llamado al servidor. Quizas no sea error de javascript sino del server, lo vas a poder ver en la pestaña network

Profesor le tengo otro dato
Resulta que estaba haciendo otro curso y me sale el mismo problema
El problema salta cuando hay más de un dato en la base de datos
Es decir, si hay uno solo no da problemas
Pero cuando hay más de uno es cuando me da el error

**Comment by josebellorin** [comment]
Solución: el nombre de la base de datos no era el mismo que el de el .js

**Comment by elariel24** [comment]
![image](https://user-images.githubusercontent.com/48065170/185440991-3432c397-9e03-407e-a4f0-8b1a7c4274e0.png)
Saludos, estoy atascado aqui, ya que no me recopila los datos en la variable Query. podria por favor colaborarme
